/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.missouri.isocial.foundation;

import edu.missouri.isocial.foundation.components.core.Connection;
import edu.missouri.isocial.foundation.components.core.ConnectionController;
import edu.missouri.isocial.foundation.components.core.Connector;
import edu.missouri.isocial.foundation.components.core.DraggableJPanel;
import edu.missouri.isocial.foundation.contextmenu.ContextMenu;

/**
 *
 * @author Ryan
 */
public class EditorCanvas extends javax.swing.JPanel implements Editor {
    
    private ContextMenu contextMenu;
    private EditorCanvasController controller;
    
    public EditorCanvas() {
        initComponents();
        
        Lookup lookup = new LookupImpl();
        controller = new EditorCanvasController(this);
        contextMenu = new ContextMenuBuilder(lookup, this).build();
    }

    @Override
    public Connection addConnection(Connector start, Connector end) {
        
        Connection connection = new Connection(start, end);
        add(connection);
        connection.setVisible(true);
        ConnectionController cc = new ConnectionController(this, start, end, connection);
        cc.setVisible(true);
        
        return connection;
    }
    
    @Override
    public void addDraggable(DraggableJPanel draggable) {
        add(draggable);
    }

    @Override
    public void showContextMenu(int xOnScreen, int yOnScreen) {
        contextMenu.show(this, xOnScreen, yOnScreen);
        contextMenu.setVisible(true);
    }
    
    @Override
    public void removeDraggable(DraggableJPanel draggable) {
        remove(draggable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
